// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange_rates.proto

package com.stockservice.proto;

public final class ExchangeRatesProto {
  private ExchangeRatesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExchangeRatesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExchangeRates)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stockExchangeName = 1;</code>
     */
    java.lang.String getStockExchangeName();
    /**
     * <code>string stockExchangeName = 1;</code>
     */
    com.google.protobuf.ByteString
        getStockExchangeNameBytes();

    /**
     * <code>string currency = 2;</code>
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 2;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    java.util.List<ExchangeRatesProto.Rate> 
        getRatesList();
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    ExchangeRatesProto.Rate getRates(int index);
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    int getRatesCount();
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    java.util.List<? extends ExchangeRatesProto.RateOrBuilder> 
        getRatesOrBuilderList();
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    ExchangeRatesProto.RateOrBuilder getRatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ExchangeRates}
   */
  public  static final class ExchangeRates extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExchangeRates)
      ExchangeRatesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRates.newBuilder() to construct.
    private ExchangeRates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRates() {
      stockExchangeName_ = "";
      currency_ = "";
      rates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangeRates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stockExchangeName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currency_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                rates_ = new java.util.ArrayList<ExchangeRatesProto.Rate>();
                mutable_bitField0_ |= 0x00000004;
              }
              rates_.add(
                  input.readMessage(ExchangeRatesProto.Rate.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          rates_ = java.util.Collections.unmodifiableList(rates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExchangeRatesProto.internal_static_ExchangeRates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExchangeRatesProto.internal_static_ExchangeRates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExchangeRatesProto.ExchangeRates.class, ExchangeRatesProto.ExchangeRates.Builder.class);
    }

    private int bitField0_;
    public static final int STOCKEXCHANGENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object stockExchangeName_;
    /**
     * <code>string stockExchangeName = 1;</code>
     */
    public java.lang.String getStockExchangeName() {
      java.lang.Object ref = stockExchangeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockExchangeName_ = s;
        return s;
      }
    }
    /**
     * <code>string stockExchangeName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStockExchangeNameBytes() {
      java.lang.Object ref = stockExchangeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockExchangeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCY_FIELD_NUMBER = 2;
    private volatile java.lang.Object currency_;
    /**
     * <code>string currency = 2;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATES_FIELD_NUMBER = 3;
    private java.util.List<ExchangeRatesProto.Rate> rates_;
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    public java.util.List<ExchangeRatesProto.Rate> getRatesList() {
      return rates_;
    }
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    public java.util.List<? extends ExchangeRatesProto.RateOrBuilder> 
        getRatesOrBuilderList() {
      return rates_;
    }
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    public int getRatesCount() {
      return rates_.size();
    }
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    public ExchangeRatesProto.Rate getRates(int index) {
      return rates_.get(index);
    }
    /**
     * <code>repeated .Rate rates = 3;</code>
     */
    public ExchangeRatesProto.RateOrBuilder getRatesOrBuilder(
        int index) {
      return rates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStockExchangeNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stockExchangeName_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currency_);
      }
      for (int i = 0; i < rates_.size(); i++) {
        output.writeMessage(3, rates_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStockExchangeNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stockExchangeName_);
      }
      if (!getCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currency_);
      }
      for (int i = 0; i < rates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, rates_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ExchangeRatesProto.ExchangeRates)) {
        return super.equals(obj);
      }
      ExchangeRatesProto.ExchangeRates other = (ExchangeRatesProto.ExchangeRates) obj;

      boolean result = true;
      result = result && getStockExchangeName()
          .equals(other.getStockExchangeName());
      result = result && getCurrency()
          .equals(other.getCurrency());
      result = result && getRatesList()
          .equals(other.getRatesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STOCKEXCHANGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getStockExchangeName().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      if (getRatesCount() > 0) {
        hash = (37 * hash) + RATES_FIELD_NUMBER;
        hash = (53 * hash) + getRatesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ExchangeRatesProto.ExchangeRates parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExchangeRatesProto.ExchangeRates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ExchangeRatesProto.ExchangeRates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExchangeRatesProto.ExchangeRates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ExchangeRatesProto.ExchangeRates prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExchangeRates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExchangeRates)
        ExchangeRatesProto.ExchangeRatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExchangeRatesProto.internal_static_ExchangeRates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExchangeRatesProto.internal_static_ExchangeRates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ExchangeRatesProto.ExchangeRates.class, ExchangeRatesProto.ExchangeRates.Builder.class);
      }

      // Construct using ExchangeRatesProto.ExchangeRates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRatesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        stockExchangeName_ = "";

        currency_ = "";

        if (ratesBuilder_ == null) {
          rates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ratesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExchangeRatesProto.internal_static_ExchangeRates_descriptor;
      }

      public ExchangeRatesProto.ExchangeRates getDefaultInstanceForType() {
        return ExchangeRatesProto.ExchangeRates.getDefaultInstance();
      }

      public ExchangeRatesProto.ExchangeRates build() {
        ExchangeRatesProto.ExchangeRates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ExchangeRatesProto.ExchangeRates buildPartial() {
        ExchangeRatesProto.ExchangeRates result = new ExchangeRatesProto.ExchangeRates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.stockExchangeName_ = stockExchangeName_;
        result.currency_ = currency_;
        if (ratesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            rates_ = java.util.Collections.unmodifiableList(rates_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.rates_ = rates_;
        } else {
          result.rates_ = ratesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ExchangeRatesProto.ExchangeRates) {
          return mergeFrom((ExchangeRatesProto.ExchangeRates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ExchangeRatesProto.ExchangeRates other) {
        if (other == ExchangeRatesProto.ExchangeRates.getDefaultInstance()) return this;
        if (!other.getStockExchangeName().isEmpty()) {
          stockExchangeName_ = other.stockExchangeName_;
          onChanged();
        }
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          onChanged();
        }
        if (ratesBuilder_ == null) {
          if (!other.rates_.isEmpty()) {
            if (rates_.isEmpty()) {
              rates_ = other.rates_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRatesIsMutable();
              rates_.addAll(other.rates_);
            }
            onChanged();
          }
        } else {
          if (!other.rates_.isEmpty()) {
            if (ratesBuilder_.isEmpty()) {
              ratesBuilder_.dispose();
              ratesBuilder_ = null;
              rates_ = other.rates_;
              bitField0_ = (bitField0_ & ~0x00000004);
              ratesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRatesFieldBuilder() : null;
            } else {
              ratesBuilder_.addAllMessages(other.rates_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ExchangeRatesProto.ExchangeRates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ExchangeRatesProto.ExchangeRates) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stockExchangeName_ = "";
      /**
       * <code>string stockExchangeName = 1;</code>
       */
      public java.lang.String getStockExchangeName() {
        java.lang.Object ref = stockExchangeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stockExchangeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stockExchangeName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStockExchangeNameBytes() {
        java.lang.Object ref = stockExchangeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockExchangeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stockExchangeName = 1;</code>
       */
      public Builder setStockExchangeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stockExchangeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stockExchangeName = 1;</code>
       */
      public Builder clearStockExchangeName() {
        
        stockExchangeName_ = getDefaultInstance().getStockExchangeName();
        onChanged();
        return this;
      }
      /**
       * <code>string stockExchangeName = 1;</code>
       */
      public Builder setStockExchangeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stockExchangeName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>string currency = 2;</code>
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currency = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 2;</code>
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 2;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 2;</code>
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currency_ = value;
        onChanged();
        return this;
      }

      private java.util.List<ExchangeRatesProto.Rate> rates_ =
        java.util.Collections.emptyList();
      private void ensureRatesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          rates_ = new java.util.ArrayList<ExchangeRatesProto.Rate>(rates_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ExchangeRatesProto.Rate, ExchangeRatesProto.Rate.Builder, ExchangeRatesProto.RateOrBuilder> ratesBuilder_;

      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public java.util.List<ExchangeRatesProto.Rate> getRatesList() {
        if (ratesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rates_);
        } else {
          return ratesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public int getRatesCount() {
        if (ratesBuilder_ == null) {
          return rates_.size();
        } else {
          return ratesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public ExchangeRatesProto.Rate getRates(int index) {
        if (ratesBuilder_ == null) {
          return rates_.get(index);
        } else {
          return ratesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder setRates(
          int index, ExchangeRatesProto.Rate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.set(index, value);
          onChanged();
        } else {
          ratesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder setRates(
          int index, ExchangeRatesProto.Rate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.set(index, builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder addRates(ExchangeRatesProto.Rate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.add(value);
          onChanged();
        } else {
          ratesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder addRates(
          int index, ExchangeRatesProto.Rate value) {
        if (ratesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRatesIsMutable();
          rates_.add(index, value);
          onChanged();
        } else {
          ratesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder addRates(
          ExchangeRatesProto.Rate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.add(builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder addRates(
          int index, ExchangeRatesProto.Rate.Builder builderForValue) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.add(index, builderForValue.build());
          onChanged();
        } else {
          ratesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder addAllRates(
          java.lang.Iterable<? extends ExchangeRatesProto.Rate> values) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rates_);
          onChanged();
        } else {
          ratesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder clearRates() {
        if (ratesBuilder_ == null) {
          rates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          ratesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public Builder removeRates(int index) {
        if (ratesBuilder_ == null) {
          ensureRatesIsMutable();
          rates_.remove(index);
          onChanged();
        } else {
          ratesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public ExchangeRatesProto.Rate.Builder getRatesBuilder(
          int index) {
        return getRatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public ExchangeRatesProto.RateOrBuilder getRatesOrBuilder(
          int index) {
        if (ratesBuilder_ == null) {
          return rates_.get(index);  } else {
          return ratesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public java.util.List<? extends ExchangeRatesProto.RateOrBuilder> 
           getRatesOrBuilderList() {
        if (ratesBuilder_ != null) {
          return ratesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rates_);
        }
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public ExchangeRatesProto.Rate.Builder addRatesBuilder() {
        return getRatesFieldBuilder().addBuilder(
            ExchangeRatesProto.Rate.getDefaultInstance());
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public ExchangeRatesProto.Rate.Builder addRatesBuilder(
          int index) {
        return getRatesFieldBuilder().addBuilder(
            index, ExchangeRatesProto.Rate.getDefaultInstance());
      }
      /**
       * <code>repeated .Rate rates = 3;</code>
       */
      public java.util.List<ExchangeRatesProto.Rate.Builder> 
           getRatesBuilderList() {
        return getRatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ExchangeRatesProto.Rate, ExchangeRatesProto.Rate.Builder, ExchangeRatesProto.RateOrBuilder> 
          getRatesFieldBuilder() {
        if (ratesBuilder_ == null) {
          ratesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ExchangeRatesProto.Rate, ExchangeRatesProto.Rate.Builder, ExchangeRatesProto.RateOrBuilder>(
                  rates_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          rates_ = null;
        }
        return ratesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExchangeRates)
    }

    // @@protoc_insertion_point(class_scope:ExchangeRates)
    private static final ExchangeRatesProto.ExchangeRates DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ExchangeRatesProto.ExchangeRates();
    }

    public static ExchangeRatesProto.ExchangeRates getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRates>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRates>() {
      public ExchangeRates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeRates(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeRates> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRates> getParserForType() {
      return PARSER;
    }

    public ExchangeRatesProto.ExchangeRates getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Rate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currency = 1;</code>
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 1;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>string price = 2;</code>
     */
    java.lang.String getPrice();
    /**
     * <code>string price = 2;</code>
     */
    com.google.protobuf.ByteString
        getPriceBytes();
  }
  /**
   * Protobuf type {@code Rate}
   */
  public  static final class Rate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Rate)
      RateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Rate.newBuilder() to construct.
    private Rate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rate() {
      currency_ = "";
      price_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Rate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currency_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              price_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExchangeRatesProto.internal_static_Rate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExchangeRatesProto.internal_static_Rate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExchangeRatesProto.Rate.class, ExchangeRatesProto.Rate.Builder.class);
    }

    public static final int CURRENCY_FIELD_NUMBER = 1;
    private volatile java.lang.Object currency_;
    /**
     * <code>string currency = 1;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private volatile java.lang.Object price_;
    /**
     * <code>string price = 2;</code>
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      }
    }
    /**
     * <code>string price = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currency_);
      }
      if (!getPriceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, price_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currency_);
      }
      if (!getPriceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ExchangeRatesProto.Rate)) {
        return super.equals(obj);
      }
      ExchangeRatesProto.Rate other = (ExchangeRatesProto.Rate) obj;

      boolean result = true;
      result = result && getCurrency()
          .equals(other.getCurrency());
      result = result && getPrice()
          .equals(other.getPrice());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ExchangeRatesProto.Rate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExchangeRatesProto.Rate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExchangeRatesProto.Rate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExchangeRatesProto.Rate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExchangeRatesProto.Rate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExchangeRatesProto.Rate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExchangeRatesProto.Rate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExchangeRatesProto.Rate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExchangeRatesProto.Rate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ExchangeRatesProto.Rate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExchangeRatesProto.Rate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExchangeRatesProto.Rate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ExchangeRatesProto.Rate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Rate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Rate)
        ExchangeRatesProto.RateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExchangeRatesProto.internal_static_Rate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExchangeRatesProto.internal_static_Rate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ExchangeRatesProto.Rate.class, ExchangeRatesProto.Rate.Builder.class);
      }

      // Construct using ExchangeRatesProto.Rate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        currency_ = "";

        price_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExchangeRatesProto.internal_static_Rate_descriptor;
      }

      public ExchangeRatesProto.Rate getDefaultInstanceForType() {
        return ExchangeRatesProto.Rate.getDefaultInstance();
      }

      public ExchangeRatesProto.Rate build() {
        ExchangeRatesProto.Rate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ExchangeRatesProto.Rate buildPartial() {
        ExchangeRatesProto.Rate result = new ExchangeRatesProto.Rate(this);
        result.currency_ = currency_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ExchangeRatesProto.Rate) {
          return mergeFrom((ExchangeRatesProto.Rate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ExchangeRatesProto.Rate other) {
        if (other == ExchangeRatesProto.Rate.getDefaultInstance()) return this;
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          onChanged();
        }
        if (!other.getPrice().isEmpty()) {
          price_ = other.price_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ExchangeRatesProto.Rate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ExchangeRatesProto.Rate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>string currency = 1;</code>
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currency = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 1;</code>
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 1;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 1;</code>
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currency_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";
      /**
       * <code>string price = 2;</code>
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          price_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string price = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string price = 2;</code>
       */
      public Builder setPrice(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string price = 2;</code>
       */
      public Builder clearPrice() {
        
        price_ = getDefaultInstance().getPrice();
        onChanged();
        return this;
      }
      /**
       * <code>string price = 2;</code>
       */
      public Builder setPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        price_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Rate)
    }

    // @@protoc_insertion_point(class_scope:Rate)
    private static final ExchangeRatesProto.Rate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ExchangeRatesProto.Rate();
    }

    public static ExchangeRatesProto.Rate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rate>
        PARSER = new com.google.protobuf.AbstractParser<Rate>() {
      public Rate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rate> getParserForType() {
      return PARSER;
    }

    public ExchangeRatesProto.Rate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExchangeRates_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExchangeRates_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Rate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024exchange_rates.proto\"R\n\rExchangeRates\022" +
      "\031\n\021stockExchangeName\030\001 \001(\t\022\020\n\010currency\030\002" +
      " \001(\t\022\024\n\005rates\030\003 \003(\0132\005.Rate\"\'\n\004Rate\022\020\n\010cu" +
      "rrency\030\001 \001(\t\022\r\n\005price\030\002 \001(\tB\024B\022ExchangeR" +
      "atesProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ExchangeRates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExchangeRates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExchangeRates_descriptor,
        new java.lang.String[] { "StockExchangeName", "Currency", "Rates", });
    internal_static_Rate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Rate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Rate_descriptor,
        new java.lang.String[] { "Currency", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
